#!/usr/bin/env node
// Builds the generated files from tokens/tokens.json and checks the system.
//   node scripts/build.mjs          build styles/tokens.css, styles/tailwind-theme.css, tokens/tokens.dtcg.json, then check
//   node scripts/build.mjs --check  check only; exits 1 if anything fails or a generated file is stale
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const p = (...parts) => join(root, ...parts);
const checkOnly = process.argv.includes("--check");
const tokens = JSON.parse(readFileSync(p("tokens/tokens.json"), "utf8"));

const PRODUCTS = ["upspire", "vsm", "nbm", "assessment", "roles", "perennial"];
const themes = tokens.color.themes.map((t) => t.id);
const first = themes[0];
const val = (t, theme) => (typeof t.value === "string" ? t.value : t.value[theme] ?? t.value[first]);
const colors = Object.fromEntries(tokens.color.tokens.map((t) => [t.name, t]));

// ---------- generate ----------
const HEADER = "/* GENERATED by scripts/build.mjs from tokens/tokens.json. Do not edit by hand. */";

function tokensCss() {
  const out = [HEADER];
  for (const theme of themes) {
    const sel = theme === first ? `:root, [data-theme="${theme}"]` : `[data-theme="${theme}"]`;
    out.push(`${sel} {`);
    for (const t of tokens.color.tokens) out.push(`  --${t.name}: ${val(t, theme)};`);
    for (const t of tokens.shadow.tokens) out.push(`  --${t.name}: ${val(t, theme)};`);
    if (theme !== first) out.push("  color-scheme: dark;");
    out.push("}");
  }
  out.push(":root {");
  for (const fam of ["spacing", "radius"]) for (const t of tokens[fam].tokens) out.push(`  --${t.name}: ${t.value};`);
  for (const [k, v] of Object.entries(tokens.type.families)) out.push(`  --font-${k}: ${v};`);
  out.push("}");
  for (const g of tokens.type.groups) {
    for (const s of g.styles) {
      const decl = [
        `font-family: var(--font-${s.family ?? g.family})`,
        `font-size: ${s.fontSize}`,
        `line-height: ${s.lineHeight}`,
        `font-weight: ${s.fontWeight}`,
      ];
      if (s.letterSpacing) decl.push(`letter-spacing: ${s.letterSpacing}`);
      if (s.name === "label") decl.push("text-transform: uppercase");
      out.push(`.${s.name} { ${decl.join("; ")}; }`);
    }
  }
  return out.join("\n") + "\n";
}

function tailwindTheme() {
  const out = [
    HEADER,
    "/* Tailwind v4: @import this after tokens.css and brands.css. Utilities read semantic tokens only. */",
    "@theme inline {",
  ];
  const semantic = ["paper", "paper-raised", "paper-sunken", "rule", "rule-strong", "ink", "ink-soft", "ink-faint", "focus",
    "success", "success-bg", "warning", "warning-bg", "danger", "danger-bg", "info", "info-bg"];
  for (const n of semantic) out.push(`  --color-${n}: var(--${n});`);
  for (const n of ["primary", "primary-hover", "primary-tint", "accent", "on-primary"]) out.push(`  --color-${n}: var(--${n});`);
  // Fonts and radii share Tailwind's own variable names, so they are written as values, not var(), to avoid self-references.
  for (const [k, v] of Object.entries(tokens.type.families)) out.push(`  --font-${k}: ${v};`);
  for (const t of tokens.radius.tokens) out.push(`  --radius-${t.name.replace(/^radius-/, "")}: ${t.value};`);
  out.push("}");
  out.push("/* Shadows change per theme: use shadow-(--shadow-card) and shadow-(--shadow-raised). */");
  return out.join("\n") + "\n";
}

function dtcg() {
  const doc = { $description: "W3C Design Tokens export of tokens/tokens.json. GENERATED; do not edit.", color: {}, spacing: {}, radius: {}, shadow: {}, font: {} };
  for (const theme of themes) {
    doc.color[theme] = {};
    for (const t of tokens.color.tokens) doc.color[theme][t.name] = { $type: "color", $value: val(t, theme), $description: t.usage };
  }
  for (const fam of ["spacing", "radius"]) for (const t of tokens[fam].tokens) doc[fam][t.name] = { $type: "dimension", $value: t.value, $description: t.usage };
  for (const t of tokens.shadow.tokens) doc.shadow[t.name] = { $type: "shadow", $value: val(t, first), $description: t.usage };
  for (const [k, v] of Object.entries(tokens.type.families)) doc.font[k] = { $type: "fontFamily", $value: v };
  for (const g of tokens.type.groups)
    for (const s of g.styles)
      doc.font[s.name] = {
        $type: "typography",
        $value: { fontFamily: `{font.${s.family ?? g.family}}`, fontSize: s.fontSize, lineHeight: s.lineHeight, fontWeight: s.fontWeight, ...(s.letterSpacing ? { letterSpacing: s.letterSpacing } : {}) },
        $description: s.usage,
      };
  return JSON.stringify(doc, null, 2) + "\n";
}

const generated = {
  "styles/tokens.css": tokensCss(),
  "styles/tailwind-theme.css": tailwindTheme(),
  "tokens/tokens.dtcg.json": dtcg(),
};

const errors = [];
for (const [file, text] of Object.entries(generated)) {
  if (checkOnly) {
    if (!existsSync(p(file)) || readFileSync(p(file), "utf8") !== text) errors.push(`${file} is stale: run npm run build`);
  } else {
    writeFileSync(p(file), text);
  }
}

// ---------- checks ----------
function lum(hex) {
  const h = hex.replace("#", "");
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255).map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function ratio(a, b) {
  const [hi, lo] = [lum(a), lum(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}
function pair(fg, bg, min) {
  for (const theme of themes) {
    if (!colors[fg] || !colors[bg]) { errors.push(`missing token in pair ${fg} on ${bg}`); return; }
    const r = ratio(val(colors[fg], theme), val(colors[bg], theme));
    if (r < min) errors.push(`contrast ${theme}: ${fg} on ${bg} is ${r.toFixed(2)}, needs ${min}`);
  }
}
const papers = ["paper", "paper-raised", "paper-sunken"];
for (const g of papers) {
  for (const t of ["ink", "ink-soft", "success", "warning", "danger", "info"]) pair(t, g, 4.5);
  pair("rule-strong", g, 3);
  pair("focus", g, 3);
}
for (const g of ["paper", "paper-raised"]) pair("ink-faint", g, 4.5);
for (const s of ["success", "warning", "danger", "info"]) pair(s, `${s}-bg`, 4.5);
for (const k of PRODUCTS) {
  for (const suffix of ["primary", "primary-hover", "tint", "accent", "on-primary"])
    if (!colors[`${k}-${suffix}`]) errors.push(`missing token ${k}-${suffix}`);
  pair(`${k}-on-primary`, `${k}-primary`, 4.5);
  pair(`${k}-on-primary`, `${k}-primary-hover`, 4.5);
  pair(`${k}-primary`, "paper", 4.5);
  pair(`${k}-primary`, "paper-raised", 4.5);
  pair(`${k}-primary`, `${k}-tint`, 4.5);
  pair("ink", `${k}-tint`, 4.5);
}

// every product has a scope and both mark files
const brandsCss = readFileSync(p("styles/brands.css"), "utf8");
for (const k of PRODUCTS) {
  if (!brandsCss.includes(`[data-brand="${k}"]`)) errors.push(`styles/brands.css has no [data-brand="${k}"] block`);
  for (const f of [`${k}-mark.svg`, `${k}-mark-reversed.svg`]) {
    const path = p("brand/marks", f);
    if (!existsSync(path)) { errors.push(`brand/marks/${f} is missing`); continue; }
    const svg = readFileSync(path, "utf8");
    if (/<image|<style|<script|<text/i.test(svg)) errors.push(`brand/marks/${f} must be plain vector shapes (no image, style, script or text)`);
  }
}

// docs only reference var(--x) tokens that exist
const known = new Set([
  ...tokens.color.tokens.map((t) => t.name),
  ...tokens.shadow.tokens.map((t) => t.name),
  ...tokens.spacing.tokens.map((t) => t.name),
  ...tokens.radius.tokens.map((t) => t.name),
  ...Object.keys(tokens.type.families).map((k) => `font-${k}`),
  "primary", "primary-hover", "primary-tint", "accent", "on-primary",
]);
for (const file of ["styles/components.css", "styles/brands.css", "components/upspire.js"]) {
  const text = readFileSync(p(file), "utf8");
  for (const m of text.matchAll(/var\(--([a-z0-9-]+)\)/g)) if (!known.has(m[1])) errors.push(`${file} uses undefined token --${m[1]}`);
}

if (errors.length) {
  console.error(`Design system check failed (${errors.length}):\n- ` + errors.join("\n- "));
  process.exit(1);
}
console.log(checkOnly ? "Design system check passed." : "Built generated files. Design system check passed.");
